export enum ActionState {
    Any = -1,
    IdleState = 0,
    MovingState = 1,
    MovingTowardTargetState = 2,
    BankingState = 3,
    MeleeCombatState = 4,
    TradingState = 5,
    ShoppingState = 6,
    FishingState = 7,
    CookingState = 8,
    RespawningState = 9,
    PlayerDeadState = 10,
    ConversationState = 11,
    ChangingAppearanceState = 12,
    WoodcuttingState = 13,
    MiningState = 14,
    HarvestingState = 15,
    TreeShakingState = 16,
    SmeltingState = 17,
    SmithingState = 18,
    CraftingState = 19,
    GoThroughDoorState = 20,
    MagicCombatState = 21,
    RangeCombatState = 22,
    EnchantingState = 23,
    TeleportingState = 24,
    NPCDeadState = 25,
    CreatingNonSkillItemsState = 26,
    SearchingWorldEntityState = 27,
    PotionMakingState = 28,
    MineThroughRocksState = 29,
    UsingSpinningWheelState = 30,
    ClimbSameMapLevelState = 31,
    SmeltingKilnState = 32,
    PlayerLoggingOutState = 33,
    PickpocketingState = 34,
    StunnedState = 35,
    PicklockingState = 36,
    NPCConversationState = 37,
    RubbingItemState = 38,
    OpeningItemState = 39,
    UsingItemOnEntityState = 40,
    DiggingState = 41,
}

/*
!function(e) {
    e[e.IdleState = 0] = "IdleState",
    e[e.MovingState = 1] = "MovingState",
    e[e.MovingTowardTargetState = 2] = "MovingTowardTargetState",
    e[e.BankingState = 3] = "BankingState",
    e[e.MeleeCombatState = 4] = "MeleeCombatState",
    e[e.TradingState = 5] = "TradingState",
    e[e.ShoppingState = 6] = "ShoppingState",
    e[e.FishingState = 7] = "FishingState",
    e[e.CookingState = 8] = "CookingState",
    e[e.RespawningState = 9] = "RespawningState",
    e[e.PlayerDeadState = 10] = "PlayerDeadState",
    e[e.ConversationState = 11] = "ConversationState",
    e[e.ChangingAppearanceState = 12] = "ChangingAppearanceState",
    e[e.WoodcuttingState = 13] = "WoodcuttingState",
    e[e.MiningState = 14] = "MiningState",
    e[e.HarvestingState = 15] = "HarvestingState",
    e[e.TreeShakingState = 16] = "TreeShakingState",
    e[e.SmeltingState = 17] = "SmeltingState",
    e[e.SmithingState = 18] = "SmithingState",
    e[e.CraftingState = 19] = "CraftingState",
    e[e.GoThroughDoorState = 20] = "GoThroughDoorState",
    e[e.MagicCombatState = 21] = "MagicCombatState",
    e[e.RangeCombatState = 22] = "RangeCombatState",
    e[e.EnchantingState = 23] = "EnchantingState",
    e[e.TeleportingState = 24] = "TeleportingState",
    e[e.NPCDeadState = 25] = "NPCDeadState",
    e[e.CreatingNonSkillItemsState = 26] = "CreatingNonSkillItemsState",
    e[e.SearchingWorldEntityState = 27] = "SearchingWorldEntityState",
    e[e.PotionMakingState = 28] = "PotionMakingState",
    e[e.MineThroughRocksState = 29] = "MineThroughRocksState",
    e[e.UsingSpinningWheelState = 30] = "UsingSpinningWheelState",
    e[e.ClimbSameMapLevelState = 31] = "ClimbSameMapLevelState",
    e[e.SmeltingKilnState = 32] = "SmeltingKilnState",
    e[e.PlayerLoggingOutState = 33] = "PlayerLoggingOutState",
    e[e.PickpocketingState = 34] = "PickpocketingState",
    e[e.StunnedState = 35] = "StunnedState",
    e[e.PicklockingState = 36] = "PicklockingState",
    e[e.NPCConversationState = 37] = "NPCConversationState",
    e[e.RubbingItemState = 38] = "RubbingItemState",
    e[e.OpeningItemState = 39] = "OpeningItemState",
    e[e.UsingItemOnEntityState = 40] = "UsingItemOnEntityState",
    e[e.DiggingState = 41] = "DiggingState"
}(DI || (DI = {}));
const BI = DI
*/