export enum ContextMenuTypes {
    Any = -1,
    Inventory = 0,
    Bank = 1,
    Shop = 2,
    TradeInventory = 3,
    TradeMyOfferedItems = 4,
    TradeOtherPlayerOfferedItems = 5,
    Loadout = 6,
    ChangeAppearance = 7,
    Smelting = 8,
    Smithing = 9,
    Magic = 10,
    QuestDetail = 11,
    PotionMaking = 12,
    Welcome = 13,
    SmeltingKiln = 14,
    CameraSettings = 15,
    SkillGuide = 16,
    Loot = 17,
    FriendList = 18,
    Stats = 19,
    Quests = 20,
    Settings = 21,
    TextInput = 22,
    Confirmation = 23,
    Chat = 24,
    PrivateChat = 25,
    TradeMenu = 26,
    TreasureMap = 27,
    GraphicsSettings = 28,
}

/*
var SF;
!function(e) {
    e[e.Inventory = 0] = "Inventory",
    e[e.Bank = 1] = "Bank",
    e[e.Shop = 2] = "Shop",
    e[e.TradeInventory = 3] = "TradeInventory",
    e[e.TradeMyOfferedItems = 4] = "TradeMyOfferedItems",
    e[e.TradeOtherPlayerOfferedItems = 5] = "TradeOtherPlayerOfferedItems",
    e[e.Loadout = 6] = "Loadout",
    e[e.ChangeAppearance = 7] = "ChangeAppearance",
    e[e.Smelting = 8] = "Smelting",
    e[e.Smithing = 9] = "Smithing",
    e[e.Magic = 10] = "Magic",
    e[e.QuestDetail = 11] = "QuestDetail",
    e[e.PotionMaking = 12] = "PotionMaking",
    e[e.Welcome = 13] = "Welcome",
    e[e.SmeltingKiln = 14] = "SmeltingKiln",
    e[e.CameraSettings = 15] = "CameraSettings",
    e[e.SkillGuide = 16] = "SkillGuide",
    e[e.Loot = 17] = "Loot",
    e[e.FriendList = 18] = "FriendList",
    e[e.Stats = 19] = "Stats",
    e[e.Quests = 20] = "Quests",
    e[e.Settings = 21] = "Settings",
    e[e.TextInput = 22] = "TextInput",
    e[e.Confirmation = 23] = "Confirmation",
    e[e.Chat = 24] = "Chat",
    e[e.PrivateChat = 25] = "PrivateChat",
    e[e.TradeMenu = 26] = "TradeMenu",
    e[e.TreasureMap = 27] = "TreasureMap",
    e[e.GraphicsSettings = 28] = "GraphicsSettings"
}(SF || (SF = {}));
const CF = SF
*/