name: Build and Release

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Enable Corepack
      run: corepack enable
      
    - name: Install Dependencies
      run: yarn install

    - name: Build HighLite
      run: yarn core:dist

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4.6.2
      with:
        name: HighliteCore
        path: dist/*
        retention-day: 1
        compression-level: 6
        overwrite: true
        include-hidden-files: false

    - name: Get Version from package.json
      id: get_version
      run: |
        VERSION=$(jq -r '.version' package.json)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "::set-output name=version::$VERSION"
        
  Release:
    needs: [Build]
    runs-on: ubuntu-latest
    
    steps:
      - name: Get Build Release Version
        run:  echo "VERSION=${{ needs.Build.outputs.version }}" >> $GITHUB_ENV
        
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4.3.0
        with:
          name: HighliteCore

      - name: Debug LS
        run: ls

      - name: Create/Update GitHub Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "dist/*"
          generateReleaseNotes: true
          prerelease: true
          tag: "v${{ env.VERSION }}"
          updateOnlyUnreleased: true
  
