on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build_Code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build the code
        run: bun run bundle.ts

      - name: Get version from package.json
        id: version
        run: |
          VERSION=$(bun -p "require('./package.json').version")
          echo "Version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Create/Update Github Release
        uses: mini-bomba/create-github-release@v1.1.3
        with:
          # Token used for creating/editing releases
          token: ${{ secrets.GITHUB_TOKEN }}
          # Tag to create/move and use for the release
          tag: "v${{ env.version }}"
          name: "v${{ env.version }}"
          body: "Highlite Core Release v${{ env.version }}"
          # Files to attach; newline seperated, recursive globbing supported
          files: dist/highliteCore.js
